global:
  scrape_interval: 15s
  scrape_timeout: "10s"

scrape_configs:
  - job_name: rottenpotatoes
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets:
        - web:5000
  
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090